#! /bin/sh 
set_path="cd /home/topperge/current" 
case "$1" in 
	start) 
		echo -n "Starting delayed_job: " 
		su - root -c "$set_path; RAILS_ENV=production script/delayed_job start" >> /var/log/delayed_job.log 2>&1 
		echo "done." 
		;; 
	stop) 
		echo -n "Stopping delayed_job: " 
		su - root -c "$set_path; RAILS_ENV=production script/delayed_job stop" >> /var/log/delayed_job.log 2>&1 
		echo "done." ;; 
	*) 
		echo "Usage: $N {start|stop}" >&2 
		exit 1 
		;; 
esac 
exit 0